language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base
  - sudo apt-get -y -qq install qt59imageformats qt59svg qt59charts-no-lgpl qt59tools
  - sudo apt-get -y -qq install qt59multimedia libmagic-dev libpulse-dev libqt5svg5
  - sudo apt-get -y -qq install qt59webengine qt59webchannel 
  - sudo apt-get -y -qq install libz-dev zlib1g-dev liblz-dev libbz2-dev libarchive-dev 
  - source /opt/qt*/bin/qt*-env.sh

script:
  ...
