language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -y -qq install qt59base libz-dev zlib1g-dev liblz-dev libbz2-dev libarchive-dev
  - sudo apt-get -y -qq install qt59imageformats qt59svg qt59charts-no-lgpl qt59tools
  - sudo apt-get -y -qq install qt59multimedia libmagic-dev libpulse-dev libqt5svg5
  - sudo apt-get -y -qq install qt59webengine qt59webchannel 

script:
  - qmake -qt5 CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

